/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://arbs535vjvd5rgwnjupcborlem.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-d264mmntxjg6xktmxiiz4zbc34",
    "aws_cognito_identity_pool_id": "us-east-1:91280cb0-bfca-4cde-9a17-aae79ef32b58",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MjtP9UV6M",
    "aws_user_pools_web_client_id": "7u5c7fpfjrgk4it5ipriehf0f",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "es-US"
                }
            },
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Mia",
                    "LanguageCode": "es-MX"
                }
            }
        }
    }
};


export default awsmobile;
